ERR2040631 data from SRA already present.
SRR9888534 data from SRA already present.
MedPlantsRNAseq data already present.
[11:58 PM]: OS: linux2, 64 cores, ~ 528 GB RAM. Python: 2.7.15
[11:58 PM]: Running funannotate v1.6.0-98d4d3f
-------------------------------------------------------
Traceback (most recent call last):
  File "/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/funannotate/git-live/bin/funannotate-train.py", line 676, in <module>
    programs = ['fasta', 'minimap2', 'blat', 'hisat2', 'hisat2-build', 'Trinity', 'java', 'kallisto', LAUNCHPASA, os.path.join(PASA, 'bin', 'seqclean')]
NameError: name 'LAUNCHPASA' is not defined
